bookstore/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, HiddenField

class AddToCart(FlaskForm):
    quantity = IntegerField('Quantity')
    id = IntegerField('ID')

bookstore/cart/routes.py
from flask import Blueprint, render_template, redirect, url_for, session, request, make_response, flash
from bookstore.cart.forms import AddToCart
from bookstore.cart.utils import handle_cart
from bookstore import dao

cart = Blueprint("cart", __name__)


@cart.route("/buyNow")
def buy_now():
    id = int(request.args.get("id"))
    if "cart" not in session:
        session["cart"] = []
    product = [prod for prod in session["cart"] if prod["id"] == int(id)]
    index = [index for index, prod in enumerate(session["cart"]) if prod["id"] == int(id)]
    if len(product) == 0:
        session["cart"].append({"id": id, "quantity": 1})
    else:
        session["cart"][index[0]]['quantity'] = product[0]['quantity'] + 1
    session.modified = True
    return redirect(url_for("cart.cartDetail"))


@cart.route("/quick-add/<int:id>")
def quickAdd(id):
    if "cart" not in session:
        session["cart"] = []

    product = [prod for prod in session["cart"] if prod["id"] == int(id)]
    index = [index for index, prod in enumerate(session["cart"]) if prod["id"] == int(id)]
    if len(product) == 0:
        session["cart"].append({"id": id, "quantity": 1})
    else:
        session["cart"][index[0]]['quantity'] = product[0]['quantity'] + 1
    session.modified = True

    return redirect(url_for("main.home"))


@cart.route("/cart")
def cartDetail():
    configuration = dao.get_configuration()
    if "cart" not in session:
        session["cart"] = []
    products, grand_total, grand_total_plus_shipping, quantity_total = handle_cart()
    return render_template("cart.html", products=products, grand_total=grand_total,
                           grand_total_plus_shipping=grand_total_plus_shipping, quantity_total=quantity_total,
                           quick_ship=configuration.quick_ship)


@cart.route("/add-to-cart", methods=["POST"])
def addToCart():
    if "cart" not in session:
        session["cart"] = []
    form = AddToCart()
    if form.validate_on_submit():
        id = int(form.id.data)
        product = [prod for prod in session["cart"] if prod["id"] == int(id)]
        index = [index for index, prod in enumerate(session["cart"]) if prod["id"] == int(id)]
        print(product, index)

        if len(product) == 0:
            session["cart"].append({"id": id, "quantity": int(form.quantity.data)})
        else:

            session["cart"][index[0]]['quantity'] = product[0]['quantity'] + int(form.quantity.data)

        session.modified = True

    return redirect(url_for('books.bookDetail', book_id=id))


@cart.route("/remove-from-cart/<int:index>")
def removeFromCart(index):
    del session["cart"][int(index)]
    session.modified = True
    next = request.args.get("next")
    if next:
        return redirect(next)
    return redirect(url_for("cart.cartDetail"))


@cart.route("/api/changeQuantity", methods=["POST"])
def change_quantity():
    index = int(request.args.get('index'))
    quantity = int(request.args.get('quantity'))
    session['cart'][index]['quantity'] = quantity
    session.modified = True
    response = make_response()
    response.status_code = 200
    return response

bookstore/main/routes.py
import math

from flask import render_template, request, Blueprint, flash, jsonify, make_response, redirect, url_for, session
from bookstore import utils, app, dao
from bookstore.models import Book
from bookstore.cart.utils import handle_cart
from flask_security import current_user
main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    cate_id = request.args.get('cate_id')
    page = request.args.get('page', 1, type=int)
    num = Book.query.filter(Book.enable.__eq__(True)).count()
    numCate = None
    if cate_id:
        num_cate_book = Book.query.filter(Book.category_id.__eq__(cate_id)).count()
        numCate = math.ceil(num_cate_book / app.config['PAGE_SIZE'])
    # if "cart" not in session:
    #     session["cart"] = []
    # products, grand_total, grand_total_plus_shipping, quantity_total = handle_cart()


    posts=dao.load_book(cate_id, page)
    if current_user.is_authenticated:
        if "cart" in session:
            products, grand_total, grand_total_plus_shipping, quantity_total = handle_cart()
            return render_template("home.html", numCate=numCate, cate_id=cate_id, posts=posts,
                                   pages=math.ceil(num / app.config['PAGE_SIZE']), quantity_total=quantity_total)

    return render_template("home.html", numCate=numCate, cate_id=cate_id,
                                   pages=math.ceil(num / app.config['PAGE_SIZE']), posts=posts)


@app.context_processor
def common_response():
    return {
        'categories': dao.load_cate()}


@main.route("/about")
def about():
    return render_template("about.html", title='About')

@main.route("/import", methods=["POST"])
def import_book():
    # get data file from form
    excel = request.files['excel']
    # handle new data
    response = make_response()

    try:
        utils.import_book(excel=excel)
        response.status_code = 200
    except:
        response.status_code= 400
    return response

@main.route("/search", methods=['GET', 'POST'])
def searchItems():
    data = request.args.get('search')
    page = request.args.get('page', 1, type=int)
    num = Book.query.filter(Book.name.contains(data)).count()

    res = dao.load_book(kw=data, page=page)
    
    if not data or num==0:
        flash('Book not found!!', 'warning')
        return redirect(url_for('main.home'))
    num=math.ceil(num/app.config['PAGE_SIZE'])

    return render_template("home.html", posts=res, num=num, kw=data)


@main.route("/statistic", methods=['GET'])
def statistic():
    month = int(request.args.get("month"))
    type = request.args.get("type")
    data = None
    if type == 'book':
        data = utils.statistic_book_by_month(month)
    if type == 'category':
        data = utils.statistic_category_by_month(month)
    if type == 'overall':
        data = utils.statistic_revenue()
    return data

bookstore/users/routes.py
from flask import render_template, request, Blueprint, url_for, redirect, flash, session, jsonify
from flask_security import logout_user, current_user, roles_accepted, login_required
from bookstore.users.forms import UpdateAccountForm, RegistrationForm, LoginForm, VerifyAccountForm
from bookstore.cart.forms import AddToCart
from bookstore.cart.utils import handle_cart
from bookstore.users.utils import save_picture, send_verify_code, verify_account, resend_register_code, extract_search_user_by_phone

from bookstore import db, user_datastore, dao
from flask_security.utils import hash_password, verify_password, login_user

users = Blueprint('users', __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = form.get_user()
        print("Register User: %s" % user)
        if not user:
            hashed_password = hash_password(form.password.data)
            new_user = user_datastore.create_user(
                username=form.username.data, email=form.email.data, password=hashed_password, active=False
            )
            db.session.commit()
            if send_verify_code(user_id=new_user.id) == 0:
                flash(f"Your account has been created! Please confirm your account by the code we sent to your email!", "success")
                return redirect(url_for("users.verify", user_id = new_user.id))
            else:
                flash(f"Invalid user", "danger")
                return redirect(url_for('users.register'))
    return render_template("register.html", title='Registration', form=form)

@users.route("/resend_verify", methods=["GET"])
def resend_verify_code():
    user_id = int(request.args.get("user_id"))
    if resend_register_code(user_id=user_id) == 0:
        flash("Resend verify code successfully", "success")
        return redirect(url_for("users.verify", user_id=user_id))
    else:
        flash("Can't resend your verify code", "danger")
        return redirect(url_for("users.verify", user_id=user_id))

@users.route("/verify_account", methods= ["GET", "POST"])
def verify():
    user_id = int(request.args.get("user_id"))
    form = VerifyAccountForm()
    if request.method.__eq__("GET"):
        return render_template("verify.html", form=form, user_id=user_id)
    elif form.validate_on_submit():
        code = form.to_code()
        if verify_account(code) == 0:
            flash(f"Your account has been verified", "success")
            return redirect(url_for('users.login'))
        else:
            flash("Can't verify your account", "danger")
            return render_template("verify.html", form=form, user_id=user_id)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()

    if form.validate_on_submit():
        user = form.get_user()
        if not user.active:
            flash("Please verify your account by the code we sent to your email", "danger")
            return redirect(url_for("users.verify", user_id=user.id))
        if user:
            login_user(user, remember=form.remember.data)
            flash(f'You have been logged in!', 'success')
            # remember previous page is required and transferred to login
            if 'book_id' in request.args:
                return redirect(url_for(request.args.get('next', 'index'), book_id=request.args['book_id']))
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    user_gender = 1 if current_user.gender else 0

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        
        if current_user.username != form.username.data \
                or form.picture.data \
                or current_user.first_name != form.firstname.data\
                or current_user.last_name != form.lastname.data\
                or current_user.phone_number != form.phone.data\
                or user_gender != form.gender.data:
            current_user.first_name = form.firstname.data
            current_user.last_name = form.lastname.data
            current_user.phone_number = form.phone.data
            current_user.gender = True if int(form.gender.data)  == 1 else False
            current_user.username = form.username.data
            db.session.commit()
            flash("Your account has been updated!", "success")
            return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.gender.default = user_gender
        form.process()
        form.firstname.data = current_user.first_name
        form.lastname.data = current_user.last_name
        form.phone.data = current_user.phone_number
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = current_user.image_file
    return render_template("account.html", title='Account',image_file=image_file, form=form)

# Decorator which specifies that a user must have at least one of the specified roles.
@users.route('/staff', methods=["GET", "POST"])
@login_required
@roles_accepted('staff', 'admin')
def staff():
    if "cart" not in session:
        session["cart"] = []
    form = AddToCart()
    
    id = form.id.data
    quantity = form.quantity.data
    print(id, quantity)
    if id is None and request.method == "POST":
        flash("Your Id book is Empty. Please input fill", "warning")
    
    if form.validate_on_submit() and id is not None and request.method == "POST":
        product = [prod for prod in session["cart"] if prod["id"] == int(id)]
        index = [index for index, prod in enumerate(session["cart"]) if prod["id"] == int(id)]
        if len(product) == 0:
            session["cart"].append({"id": id, "quantity": quantity})
        else:
            session["cart"][index[0]]['quantity'] = product[0]['quantity'] + quantity
        session.modified = True
    elif request.method == "GET":
        form.id.data = ""
        form.quantity.data = 1
    products, grand_total, grand_total_plus_shipping, quantity_total = handle_cart()
    return render_template("staff.html", title='Staff Action',form=form, products=products, grand_total=grand_total, quantity_total=quantity_total)

@users.route("/api/user/search_by_phone", methods=["GET"])
@login_required
def process_search_user_by_phone():
    try:
        keyword = request.args.get("kw")
        max = int(request.args.get("max"))
        return jsonify(extract_search_user_by_phone(keyword, max))
    except:
        return jsonify([])

bookstore/templates/bookDetail.html
{% extends "layout.html" %} {% block content %}

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata d-flex justify-content-between align-items-center">
            <h2><a class="article-title text-decoration-none"
            >{{ post.name }}</a>
            </h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb align-items-center m-0">
                    <li>
                        <img
                                class="rounded-circle account-img"
                                style="
                                width: 30px;
                                height: 30px;
                                margin: 0px 10px 0px 0;
                            "
                                src="{{ post.image_src}}"
                        />
                    </li>
                    <li class="breadcrumb-item">
                        <a class="me-2 text-decoration-none">{{ post.author.name }}</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <small class="text-muted"
                        >{{ post.category.name }}</small
                        >
                    </li>
                </ol>
            </nav>
        </div>

        <figure class="figure w-100 mt-2">
            <div class="">
                <img
                        src="{{ post.image_src}}"
                        class="figure-img img-fluid img-thumbnail object-fit-cover border rounded shadow"
                        style="
                        width: 250px;
                    "
                        alt="..."
                />
            </div>
            <figcaption class="figure-caption article-content">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#Code</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Author</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">{{post.id}}</th>
                        <td>{{post.name}}</td>
                        <td>{{post.category.name}}</td>
                        <td>{{post.author.name}}</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <span class="short-description" id="short-description">{{ post.description | truncate(200) }}</span>
                    <span class="full-description" id="full-description"
                          style="display: none;">{{ post.description }}</span>
                    <button class="see_more" onclick="toggleDescription()">Xem thêm</button>
                </div>
            </figcaption>
        </figure>
    </div>
</article>


{% if  current_user.is_authenticated %}
<div>
    <textarea id="commentId" class="form-control" placeholder="Nhập nội dung bình luận"></textarea>
    <input onclick="addComment({{ post.id }})" type="button" class="btn btn-danger" style="margin-top: 7px"
           value="Bình luận"/>
</div>
{% else %}
<a href="{{ url_for('users.login', next='books.bookDetail', book_id=post.id) }}">Đăng nhập để bình luận</a>
{% endif %}

<br></br>

{% if pages>1 %}
<ul class="pagination mt-1">
    {% for i in range(1, 1+pages) %}
    <li class="page-item"><a class="page-link" href="javascript:;" onclick="loadComments({{ post.id }}, {{ i }})">{{ i
        }}</a></li>
    {% endfor %}
</ul>
{% endif %}

<div id="commentArea">


</div>


<script>
    window.onload=function (){
        loadComments({{ post.id }})
        {#let date=document.getElementsByClassName('myDate')#}
        {#for (let i=0; i<date.length;i++)#}
        {#    date[i].innerText = moment(date[i].innerText).locale('vi').fromNow()#}
        {##}
    }
</script>

{% endblock content %}

{% block index %}
<div class="content-section">
    <h3>Our Detail</h3>
    <p class='text-muted'>You can put any information here you'd like.
    <ul class="list-group">
        <li class="list-group-item list-group-item-light d-flex justify-content-between"><span>Price</span><span
                class="fw-bold">{{ "{:,.0f}".format(post.unit_price) }} VNĐ</span></li>
        <li class="list-group-item list-group-item-light d-flex justify-content-between"><span>Status</span><span
                class="fw-bold">{% if post.enable %} {{ "Available" }} {% else %} {{ "Not availble" }} {% endif %}</span>
        </li>
        <li class="list-group-item list-group-item-light d-flex justify-content-between"><span>Stock</span><span
                class="fw-bold">{{post.available_quantity}}</span></li>
        <li class="list-group-item list-group-item-light d-flex justify-content-between">etc</li>
    </ul>
    </p>

    <div class="">Quantity</div>
    <form action="{{ url_for('cart.addToCart') }}" method="POST" class="d-flex justify-content-between gap-2">
        {% if post.in_stock() > 0 %}
        <div class="w-100">
            {{ form.csrf_token }}

            {{ form.quantity(class='form-control', type='number', min=1, max=post.in_stock(), step=1, value=1) }}

            {{ form.id(class='visually-hidden', value=post.id) }}
        </div>
        {% endif %}
        <div class="panel-footer" style="white-space: nowrap;">
            {% if post.available_quantity > 0 %}
            <button type="submit" class="btn btn-info text-white">
                <i class="bi bi-cart-plus-fill"></i> Add Cart
            </button>
            {% endif %}
        </div>
    </form>
    <a
            class="btn btn-primary mt-3 w-100"
            role="button"
            aria-disabled="true"
            href="{{url_for('cart.buy_now', id=post.id)}}"
    >Buy Now</a
    >
</div>
{% endblock index %}

bookstore/templates/forget_password.html
{% extends "layout.html" %} {% block body %}
    <div class=" d-flex justify-content-center " style="margin-top: 15rem">
        <div class="content-section  w-50">
            <form method="POST" action="{{ url_for("users.forget_password") }}">
                <fieldset class="form-group">
                    <div class="form-group mt-2 d-flex flex-column">
                        <label class="form-control-label" for="email">Enter you email. We'll sent a code to your email
                        </label>
                        <input required id="email" type="email" class="form-control form-control-lg mt-2" name="email">
                    </div>
                </fieldset>
                <div class="form-group  mt-4  d-flex justify-content-sm-center">
                    <button class="btn btn-primary btn-lg w-25
                ">
                        Go!!
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock body %}

bookstore/templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Bookstore</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#headerBookStore"
            aria-controls="headerBookStore"
            aria-expanded="true"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="headerBookStore">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Category
                    </a>
                    <ul class="dropdown-menu" >
                        {% for c in categories %}
                            <li><a class="dropdown-item" href="/?cate_id={{c.id}}">{{ c.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.about')}}"
                        >About</a
                    >
                </li>
            </ul>
            <form
                class="d-flex"
                role="search"
                action="{{ url_for('main.searchItems') }}"
            >
                <input
                    class="form-control me-2"
                    type="search"
                    name="search"
                    placeholder="Search"
                    aria-label="Search"
                />
                <button class="btn btn-outline-success" type="submit">
                    Search
                </button>
            </form>
            <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto pl-3">
                <a
                    type="button"
                    class="btn btn-primary me-3 btn-sm position-relative h-100"
                    style="top: 5px"
                    href="{{url_for('cart.cartDetail')}}"
                >
                    <i class="bi-bag-plus-fill mx-1"></i> Cart
                    <span
                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                        >{{quantity_total}}</span
                    >
                </a>
                {% if current_user.is_authenticated %}
                <div class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Account
                    </a>
                    <ul class="dropdown-menu" style="left: -4.5rem">
                        <li>
                            <a
                                class="dropdown-item"
                                href="{{url_for('users.account')}}"
                                >Profile</a
                            >
                        </li>
                        <li>
                            {% if current_user.has_role('staff') %}
                            <a
                                class="dropdown-item"
                                href="{{url_for('users.staff')}}"
                                >Staff Action</a
                            >
                            {% endif %}
                        </li>
                        <li>
                            <a
                                class="dropdown-item"
                                href="{{url_for('orders.orderBooks')}}"
                                >Order Books</a
                            >
                        </li>
                        <li><hr class="dropdown-divider" /></li>
                        <li>
                            <a
                                class="dropdown-item"
                                href="{{url_for('users.logout')}}"
                                >Logout</a
                            >
                        </li>
                    </ul>
                </div>
                {% if current_user.has_role('superuser') %}
                <a
                    class="btn btn-primary"
                    role="button"
                    href="{{ url_for('admin.index') }}"
                    >Go to admin!</a
                >
                {% endif %} {% else %}
                <a class="btn btn-sm" href="{{url_for('users.register')}}"
                    >Register</a
                >
                <a
                    class="btn btn-primary text-white btn-sm"
                    role="button"
                    href="{{url_for('users.login')}}"
                    >Login</a
                >
                {% endif %}
            </div>
        </div>
    </div>

</nav>

bookstore/templates/home.html
{% extends "layout.html" %} {% block body %}

<h1 class=" h1">Welcome to Home Page</h1>
<div class="grid-container mt-2">
    {% for post in posts %}
    <article class="media content-section cart">
        <div class="media-body">
            <div class="article-metadata">
                <nav aria-label="breadcrumb">
                    <ol
                        class="breadcrumb align-items-center w-100 "
                    >
                        <li>
                            <img
                                class="rounded-circle account-img"
                                style="
                                    width: 30px;
                                    height: 30px;
                                    margin: 0px 10px 0px 0;
                                "
                                src="{{post.image_src}}"
                            />
                        </li>
                        <li class="breadcrumb-item">
                            <a class="text-decoration-none">{{ post.author.name }}</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            <small class="text-muted"
                                >{{ post.category.name }}</small
                            >
                        </li>
                    </ol>
                </nav>
            </div>
            <h2 class="d-inline-blocks text-truncate w-100">
                <a  style="text-decoration: none"
                    class=""
                    href="{{url_for('books.bookDetail', book_id=post.id)}}"
                    >{{ post.name }}</a
                >
            </h2>
            <figure class="figure w-100">
                <div class="ratio ratio-1x1">
                    <img
                        src="{{post.image_src}}"
                        class="figure-img img-fluid rounded"
                        alt="..."
                    />
                </div>
                <div class="article-description mt-2"
                     style="font-size: 20px; color:red;"       >
                    {{ "{:,.0f}".format(post.unit_price) }} VND</div>
            </figure>
        </div>
        <div class="float-end" style="">
            {% if post.in_stock() > 0 %}
                <a
                    class="btn btn-info text-white btn-sm me-2 icon-link icon-link-hover align-items-baseline"
                    role="button"
                    aria-disabled="true"
                    href="{{ url_for('cart.quickAdd', id=post.id) }}"
                    ><i class="bi bi-cart-plus-fill me-2"></i> Add Cart</a
                >
                <a
                    class="btn btn-primary btn-sm"
                    role="button"
                    aria-disabled="true"
                    href="{{url_for('cart.buy_now', id=post.id)}}"
                    >Buy Now</a
                >
            {% endif %}
        </div>
    </article>
    {% endfor %}
</div>

{% if cate_id == None%}
    {% if pages>1 %}
<ul class="pagination mt-1">
        {% for i in range(pages) %}
        <li class="page-item"><a class="page-link" href="/?page={{ i + 1 }}">{{ i + 1 }}</a></li>
        {% endfor %}
</ul>
    {% endif %}
{% endif %}


    {% if cate_id   %}
        {% if  numCate>1%}
            <ul class="pagination mt-1">
                {% for i in range(numCate) %}
                    <li class="page-item">
                        <a class="page-link" href="/?cate_id={{ cate_id }}&page={{ i + 1 }}">{{ i + 1 }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}{% endif %}



    {% if kw   %}

        {% if num>1 %}
            <ul class="pagination mt-1">
                {% for i in range(num) %}
                    <li class="page-item">
                        <a class="page-link" href="?search={{ kw }}&page={{ i + 1 }}">{{ i + 1 }}</a>
                    </li>
                {% endfor %}
            </ul>

    {% endif %}{% endif %}

    
{% endblock body %}

bookstore/templates/my_master.html
{% extends 'admin/base.html' %} {% block access_control %} {% if
current_user.is_authenticated %}
<div class="navbar-text btn-group pull-right">
    <a
        href="#"
        class="dropdown-toggle"
        data-toggle="dropdown"
        role="button"
        aria-expanded="false"
    >
        <i class="glyphicon glyphicon-user"></i>
        {% if current_user.first_name -%} {{ current_user.first_name }} {% else
        -%} {{ current_user.email }} {%- endif %}<span class="caret"></span
    ></a>
    <ul class="dropdown-menu" role="menu">
        <li style="text-align: center">
            <a style="color: black" href="{{ url_for('security.logout') }}"
                >Log out</a
            >
        </li>
    </ul>
</div>
{% endif %} {% endblock %}